# Generated by Django 4.0.8 on 2023-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reviews_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_qty',
            field=models.IntegerField(),
        ),
    ]
